# Generated by Django 6.0.1 on 2026-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Para URLs amigables si lo necesitas', max_length=200, unique=True)),
                ('descripcion_corta', models.TextField(max_length=300)),
                ('tipo', models.CharField(choices=[('PENTEST', 'Pentesting'), ('HARDENING', 'Hardening de Sistemas'), ('AUDITORIA', 'Auditoría de Cumplimiento'), ('SOC', 'Implementación SOC Básico'), ('OTROS', 'Otros Servicios')], default='PENTEST', max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('url_blog', models.URLField(max_length=500, verbose_name='Enlace al artículo en WordPress')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
